name: Contoso-Function

env:
  PROJECT_FILE: src/Contoso.FunctionApp/Contoso.FunctionApp.csproj
  FUNCTION_APP_NAME: contosofunction
# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths: 
      - src/Contoso.FunctionApp/**
      - .github/workflows/contoso-fuction.yml
    branches: 
    - master
    
jobs:
  build:
    name: BUILD FUNCTION
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
     
      - name: Install dependencies
        run: dotnet restore ${{env.PROJECT_FILE}} 
      
      - name: BuildApp
        run: dotnet publish ${{env.PROJECT_FILE}} -c Release --no-restore 
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Contosofunction
          path: src/Contoso.FunctionApp/bin/Release/netcoreapp3.1/publish
  
  deploy:
    name: DEPLOY TO FUNCTION APP
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: Contosofunction
          path: ${{github.workspace}}
      - run: ls        
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{secrets.CONTOSO_POLICY_CREDS}}
          
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.1.8
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: ${{github.workspace}}
