name: "REST API Static Security Testing"

on:
  push:
    branches: [ master ]
    paths:
    - src/Contoso.WebApi/**
    - .github/workflows/restapi-analysis.yml
  pull_request:
    branches: [ master ]
    paths:
    - src/Contoso.WebApi/**
    - .github/workflows/restapi-analysis.yml
  schedule:
    - cron: '15 0 * * 6'

env:
  API_URL: 'https://contosoplicyapi.azurewebsites.net/swagger/v1/swagger.json'

jobs:
  rest-api-static-security-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install requests library
        run: pip install requests
      
      - name: Get Rest API json
        shell: python
        run: |
          from requests import get
          from json import dump
          with open('swagger.json','w') as swaggerfile:
              dump(get('${{ env.API_URL }}').json(),swaggerfile)
              swaggerfile.close()
                
      - name: REST API Static Security Testing
        uses: 42Crunch/api-security-audit-action@v1
        with:
          api-token: ${{ secrets.API_TOKEN }}
          min-score: 15
          upload-to-code-scanning: true
          github-token: ${{ github.token }}
          workdir: /home/runner/work/ContosoPolicy/ContosoPolicy/src/Contoso.WebApi/bin/Release/netcoreapp3.1/publish
