name: "REST API Static Security Testing"

# follow standard Code Scanning triggers
on:
  push:
    branches: [ master ]
    paths:
    - src/Contoso.WebApi/**
    - .github/workflows/restapi-analysis.yml
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '15 0 * * 6'
  
jobs:
  rest-api-static-security-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get Rest API
        shell: python
        run: |
          from requests import get
          from json import dump
          with open('swagger.json','w') as swaggerfile:
              dump(get('https://contosoplicyapi.azurewebsites.net/swagger/v1/swagger.json').json(),swaggerfile)
              swaggerfile.close()
                
      - name: REST API Static Security Testing
        uses: 42Crunch/api-security-audit-action@v1
        with:
          api-token: ${{ secrets.API_TOKEN }}
          min-score: 85
          upload-to-code-scanning: true
          github-token: ${{ github.token }}
          workdir: /home/runner/work/ContosoPolicy/ContosoPolicy/src/Contoso.WebApi/bin/Release/netcoreapp3.1/publish
